// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2zA7HwKG_DERQNOH3dLfHdQYJts0GuRg',
    appId: '1:238030420530:web:8bf990cddf581603b95a2b',
    messagingSenderId: '238030420530',
    projectId: 'ihistorican',
    authDomain: 'ihistorican.firebaseapp.com',
    storageBucket: 'ihistorican.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL8F7mp_Hb1S7QsvKzgbpZcpNxOkVryQM',
    appId: '1:238030420530:android:0782e86463678ff1b95a2b',
    messagingSenderId: '238030420530',
    projectId: 'ihistorican',
    storageBucket: 'ihistorican.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDndMpH5d4KjlF8tIPzWpe-KBtx25eevs4',
    appId: '1:238030420530:ios:13cfdccd90225a1db95a2b',
    messagingSenderId: '238030420530',
    projectId: 'ihistorican',
    storageBucket: 'ihistorican.appspot.com',
    iosBundleId: 'com.example.csiProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDndMpH5d4KjlF8tIPzWpe-KBtx25eevs4',
    appId: '1:238030420530:ios:13cfdccd90225a1db95a2b',
    messagingSenderId: '238030420530',
    projectId: 'ihistorican',
    storageBucket: 'ihistorican.appspot.com',
    iosBundleId: 'com.example.csiProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2zA7HwKG_DERQNOH3dLfHdQYJts0GuRg',
    appId: '1:238030420530:web:3815f0367a2594bcb95a2b',
    messagingSenderId: '238030420530',
    projectId: 'ihistorican',
    authDomain: 'ihistorican.firebaseapp.com',
    storageBucket: 'ihistorican.appspot.com',
  );
}
